apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-predictor-deployment
spec:
  selector:
    matchLabels:
      app: iris-fastapi-service
  template:
    metadata:
      labels:
        app: iris-fastapi-service
    spec:
      containers:
      - name: iris-fastapi-service
        image: containersoga/iris-fastapi-service:v1
        ports:
        - containerPort: 80
        env:
        - name: MODEL_FILE_NAME
          value: "iris_model.pkl"
---
apiVersion: v1
kind: Service
metadata:
  name: iris-predictor-service
spec:
  selector:
    app: iris-fastapi-service
  ports:
  - port: 8089
    targetPort: 80
    name: http
  type: LoadBalancer

