apiVersion: v1
kind: PersistentVolume
metadata:
  name: traindemo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/trainvolume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traindemo-pvc
spec:
  volumeName: traindemo-pv
  storageClassName: local-storage
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1G
